- src/main/java/com/lgcns/backend/Like/domain/Like.java
- src/main/java/com/lgcns/backend/Like/repository/LikeRepository.java
- src/main/java/com/lgcns/backend/comment/domain/Comment.java
- src/main/java/com/lgcns/backend/comment/respository/CommentRepository.java
- src/main/java/com/lgcns/backend/csanswer/domain/CSAnswer.java
- src/main/java/com/lgcns/backend/csanswer/repository/CSAnswerRepository.java
- src/main/java/com/lgcns/backend/csquestion/domain/CSQuestion.java
- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestiomRepository.java
- src/main/java/com/lgcns/backend/global/domain/Category.java
- src/main/java/com/lgcns/backend/post/domain/Post.java
- src/main/java/com/lgcns/backend/post/respository/PostRepository.java
- src/main/java/com/lgcns/backend/user/domain/User.java
- src/main/java/com/lgcns/backend/user/repository/UserRepository.java
> fix: refactor files

- src/main/java/com/lgcns/backend/csanswer/dto/CSAnswerRequest.java
- src/main/java/com/lgcns/backend/csanswer/dto/CSAnswerResponse.java
파일생성
- CSAnswerRequest DTO
- CSAnswerResponse DTO
> feat: CSAnswerRequest DTO, CSAnswerResponse DTO

- src/main/java/com/lgcns/backend/csanswer/controller/CSAnswerController.java
- src/main/java/com/lgcns/backend/csanswer/repository/CSAnswerRepository.java
- src/main/java/com/lgcns/backend/csanswer/service/CSAnswerService.java
CSAnswer 관련 Controller, Service 파일 생성
- CSAnswerController
- CSAnswerService
- 답변 생성, 내 답변 리스트 조회, 내 답변 상세 조회, 답변 수정, 답변 삭제
- 로그인 기능 구현 완료 전으로, User 객체 부분 하드코딩으로 구현.
> feat: implement csanswer crud controller and service

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/domain/CSQuestion.java
- src/main/java/com/lgcns/backend/csquestion/dto/CSQuestionResponse.java
- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
#17 
CS 질문 리스트 조회 
questions?category=운영체제
카테고리가 안 넘어온 경우에는 questions/{category} 대신 request param으로 처리하는 게 더 좋을 것 같아서 수정했습니다
특정 CS 질문 조회
questions/{id}
> Feat/#17 CS 질문 조회 기능 구현

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
> Feat/#24 오늘의 질문 조회

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
#27 
CS질문 리스트 조회 시 페이지네이션 구현
Pageable 추가
> Feat/#27 CS질문 리스트 조회 시 페이지네이션 구현

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
#27 
CS 질문 리스트 페이지네이션 구현
ex) /questions?page=1?category=운영체제
> Feat/#27 CS 질문 리스트 페이지네이션 구현

- src/main/java/com/lgcns/backend/csquestion/domain/CSQuestion.java
- src/main/java/com/lgcns/backend/user/controller/UserController.java
- src/main/java/com/lgcns/backend/user/dto/request/UpdateUserRequestDto.java
- src/main/java/com/lgcns/backend/user/repository/UserRepository.java
- src/main/java/com/lgcns/backend/user/service/UserService.java
#10 
- 회원 탈퇴 기능 구현 및 테스트 완료
- 회원 정보 수정 기능 및 테스트 완료
> feat: 회원 탈퇴 및 회원 정보 수정 기능 구현 및 테스트 완료

- src/main/java/com/lgcns/backend/csanswer/controller/CSAnswerController.java
- src/main/java/com/lgcns/backend/csanswer/service/CSAnswerService.java
- CSAnwerController, CSAnswerService 인증 관련 코드 적용
> feat: CSAnswerController and CSAnswerService User 인증 추가

- src/main/java/com/lgcns/backend/csanswer/service/CSAnswerService.java
- CSAnswerService user 관련 필요없는 코드 제거 (메소드, 주석, 코드)
- CSAnswerService 코드 순서 통일
> refactor: remove unnecessary code and reorder methods in CSAnswerService

- build.gradle
- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
- src/main/java/com/lgcns/backend/security/config/WebConfig.java
- src/main/resources/application-deploy.properties
- src/main/resources/application-dev.properties
#10 
- 배포 환경을 위해 application.properties를 나눔
- securityconfig에 cors추가, webmvc로 controller cors 추가
> feat: cors 구현 및 배포 환경 준비

- build.gradle
- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
- src/main/java/com/lgcns/backend/security/config/WebConfig.java
- src/main/resources/application-deploy.properties
- src/main/resources/application-dev.properties
> refactor:dev, deploy properties

- src/main/java/com/lgcns/backend/csanswer/controller/AIFeedbackController.java
- src/main/java/com/lgcns/backend/csanswer/dto/AIRequest.java
- src/main/java/com/lgcns/backend/csanswer/dto/AIResponse.java
- src/main/java/com/lgcns/backend/csanswer/dto/CSAnswerResponse.java
- src/main/java/com/lgcns/backend/csanswer/service/AIFeedbackService.java
- CSAnswer AI Feedback 생성 관련 AIFeedbackController, AIFeedbackService 구현 완료
- AI Feedback 관련 DTO 구현 완료
- AIRequest 생성
- AIResponse 생성
- CSAnswerResponse 수정
> feat: Implement AIFeedbackController, AIFeedbackService, and related DTOs

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
> feat: cs 질문 리스트 내림차순 정렬

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
> Feat/#40 CS 질문 리스트 내림차순 정렬

- Jenkinsfile
- src/main/java/com/lgcns/backend/WebRestController.java
- src/main/java/com/lgcns/backend/csanswer/service/AIFeedbackService.java
#48 
- 젠킨스 파이프라인 작업
- healthcheck controller
> feat: jenkinsfile, webrestcontroller 구현

- Jenkinsfile
- src/main/java/com/lgcns/backend/WebRestController.java
- src/main/java/com/lgcns/backend/csanswer/service/AIFeedbackService.java
#48 
- openai api key credential 추가
> [refactor]: openaiapikey credential env add

- Jenkinsfile
> [fix]: specify correct git branch for jenkins

- Jenkinsfile
> [fix]: 도커이미지명 소문자로

- Dockerfile
> [feat]: dockerfile add

- Dockerfile
- Jenkinsfile
- src/main/resources/application-deploy1.properties
- src/main/resources/application-deploy2.properties
> [fix]: fix for deploy

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
#62 
삭제 기능 구현
질문이 검색 안될 경우 예외 처리
> Feat/#62 CS 질문 삭제 기능 구현

- src/main/java/com/lgcns/backend/BackendApplication.java
- src/main/java/com/lgcns/backend/csanswer/controller/CSAnswerController.java
- src/main/java/com/lgcns/backend/csquestion/controller/AIQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/scheduler/AIQuestionScheduler.java
[ FEATURE ] cs-question-ai-create
- OpenAI API를 사용한 CS질문 자동 생성 Scheduler 구현 완료
- BackendApplication.java @EnableScheduling 추가
- AIQuestionScheduler.java 파일 생성
> Feat: OpenAI CSQuestion 자동 생성 스케줄링 기능 구현

- src/main/java/com/lgcns/backend/csquestion/controller/CSQuestionController.java
- src/main/java/com/lgcns/backend/csquestion/dto/CSQuestionResponse.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
#64 
문제리스트 제출 정보 조회
로그인 안한 사용자는 모두 미제출
> Feat/#64 문제 리스트 제출 정보 조회

- src/main/java/com/lgcns/backend/post/controller/PostController.java
> fix: 게시글 질문 null

- Jenkinsfile
- build.gradle
- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
- src/main/java/com/lgcns/backend/user/config/AwsS3Config.java
- src/main/java/com/lgcns/backend/user/controller/UserController.java
- src/main/java/com/lgcns/backend/user/dto/request/SignUpRequestDto.java
- src/main/java/com/lgcns/backend/user/dto/request/UpdateUserRequestDto.java
- src/main/java/com/lgcns/backend/user/service/S3Service.java
- src/main/java/com/lgcns/backend/user/service/UserService.java
#10 
- S3 버킷 추가 : 사용자 프로필 이미지 저장
> [feat]: s3 bucket for user logic

- Jenkinsfile
> [fix]: jenkinsfile env name fix

- src/main/java/com/lgcns/backend/ai/config/AIConfig.java
- src/main/java/com/lgcns/backend/csanswer/domain/CSAnswer.java
- src/main/java/com/lgcns/backend/csanswer/service/AIFeedbackService.java
[[ FEATURE ] cs-answer-crud](https://github.com/lgcnsCampMprjTeam2/BackEnd/issues/4)
- CSAnswer 엔티티 클래스 내 오타 수정(ID)
- AI 피드백 기능 구현을 위한 AIConfig 파일 생성 및 그에 따른 AIFeedbackService 코드 수정
> feat: AI 피드백 기능 구현을 위한 AIConfig 파일 생성 및 AIFeedbackService 수정

- src/test/java/com/lgcns/backend/unit/aiQuestion/service/AIQuestionServiceTest.java
[[ FEATURE ] cs-question-ai-create](https://github.com/lgcnsCampMprjTeam2/BackEnd/issues/43)
- AIQuestionService 단위 테스트 코드 작성 완료
> test: AIQuestionService 단위 테스트 코드 작성

- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
> feat: 오늘의 문제 여러개일 경우 하나만 조회

- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
#78 
오늘의 문제가 여러개 있는 경우(오류) 최신순 하나만 조회하도록 수정
> Feat/#78 오늘의 문제 여러개일 경우 하나만 조회

- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
> refactor: 오늘의 문제 조회 날짜 수정

- src/main/java/com/lgcns/backend/csquestion/repository/CSQuestionRepository.java
- src/main/java/com/lgcns/backend/csquestion/service/CSQuestionService.java
> Feat/#78 오늘의 질문 날짜 수정

- Jenkinsfile
- build.gradle
- src/main/java/com/lgcns/backend/auth/controller/AuthController.java
- src/main/java/com/lgcns/backend/auth/dto/JWTokenResponse.java
- src/main/java/com/lgcns/backend/auth/service/AuthService.java
- src/main/java/com/lgcns/backend/global/code/GeneralErrorCode.java
- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
- src/main/java/com/lgcns/backend/security/filter/JwtAuthFilter.java
- src/main/java/com/lgcns/backend/security/util/JwtUtil.java
- src/main/java/com/lgcns/backend/user/config/RedisConfig.java
- src/main/java/com/lgcns/backend/user/controller/UserController.java
- src/main/java/com/lgcns/backend/user/dto/request/SignUpRequestDto.java
- src/main/java/com/lgcns/backend/user/service/UserService.java
#10 
#48
- 시큐리티 설정 변경
- 리프레시 토큰 기능 추가
- 충돌 병합
> feat, fix: refresh token 기능 구현 및 user logic refactor

- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
> fix: 게시글, 댓글 관련 권한 허가

- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
> fix: 게시글 , 댓글 관련 권한 허가

- src/main/java/com/lgcns/backend/post/controller/PostController.java
- src/main/java/com/lgcns/backend/post/dto/PostResponse.java
- src/main/java/com/lgcns/backend/post/entity/Post.java
> fix: 게시글 response

- src/main/java/com/lgcns/backend/comment/dto/CommentResponse.java
> fix: 댓글 response

- Jenkinsfile
> [fix]: container remove bug fix by wait

- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
> fix: CORS patch

- src/main/java/com/lgcns/backend/security/config/SecurityConfig.java
> Add: 프론트배포환경 허용

- src/main/java/com/lgcns/backend/csanswer/domain/CSAnswer.java
> [fix]: ai feedback 문자열 길이 문제 @Lob로 해결

- src/main/java/com/lgcns/backend/Like/repository/LikeRepository.java
- src/main/java/com/lgcns/backend/comment/respository/CommentRepository.java
- src/main/java/com/lgcns/backend/post/respository/PostRepository.java
- src/main/java/com/lgcns/backend/user/service/UserService.java
> [fix]: 회원 탈퇴 연관 테이블 회원 정보 삭제

- src/main/java/com/lgcns/backend/user/service/UserService.java
> [fix]: 회원 탈퇴 연관 테이블 회원 정보 log code

- src/main/java/com/lgcns/backend/csanswer/service/AIFeedbackService.java
[[ FEATURE ] cs-answer-crud](https://github.com/lgcnsCampMprjTeam2/BackEnd/issues/4)
- AI 피드백 프롬프트 코드 보완 및 수정
- AIFeedbackService.java 파일 수정
> fix: AI 피드백 프롬프트 코드 보완 및 수정
